-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 19:43:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myreview
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myreview` ;

-- -----------------------------------------------------
-- Schema myreview
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myreview` DEFAULT CHARACTER SET utf8 ;
USE `myreview` ;

-- -----------------------------------------------------
-- Table `myreview`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`course` ;

CREATE TABLE IF NOT EXISTS `myreview`.`course` (
  `courseId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `userId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`courseId`),
  INDEX `fk_course_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_course_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`kyc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`kyc` ;

CREATE TABLE IF NOT EXISTS `myreview`.`kyc` (
  `kycId` INT NOT NULL AUTO_INCREMENT,
  `card` VARCHAR(255) NOT NULL,
  `selfieWithCard` VARCHAR(255) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`kycId`),
  INDEX `fk_kyc_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_kyc_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`message` ;

CREATE TABLE IF NOT EXISTS `myreview`.`message` (
  `messageId` INT NOT NULL AUTO_INCREMENT,
  `senderId` INT NOT NULL,
  `receiverId` INT NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`messageId`),
  INDEX `fk_message_user1_idx` (`senderId` ASC) VISIBLE,
  INDEX `fk_message_user2_idx` (`receiverId` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`senderId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user2`
    FOREIGN KEY (`receiverId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`objective`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`objective` ;

CREATE TABLE IF NOT EXISTS `myreview`.`objective` (
  `objectiveId` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(255) NULL,
  `courseId` INT NOT NULL,
  PRIMARY KEY (`objectiveId`),
  INDEX `fk_objective_course1_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `fk_objective_course1`
    FOREIGN KEY (`courseId`)
    REFERENCES `myreview`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`post` ;

CREATE TABLE IF NOT EXISTS `myreview`.`post` (
  `postId` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `threadId` INT NULL,
  `courseId` INT NULL,
  `userId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  PRIMARY KEY (`postId`),
  INDEX `fk_post_thread1_idx` (`threadId` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_post_course1_idx` (`courseId` ASC) VISIBLE,
  CONSTRAINT `fk_post_thread1`
    FOREIGN KEY (`threadId`)
    REFERENCES `myreview`.`thread` (`threadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_course1`
    FOREIGN KEY (`courseId`)
    REFERENCES `myreview`.`course` (`courseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`postImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`postImage` ;

CREATE TABLE IF NOT EXISTS `myreview`.`postImage` (
  `postImageId` INT NOT NULL AUTO_INCREMENT,
  `postId` INT NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`postImageId`),
  INDEX `fk_postImage_post1_idx` (`postId` ASC) VISIBLE,
  CONSTRAINT `fk_postImage_post1`
    FOREIGN KEY (`postId`)
    REFERENCES `myreview`.`post` (`postId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`role` ;

CREATE TABLE IF NOT EXISTS `myreview`.`role` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`tag` ;

CREATE TABLE IF NOT EXISTS `myreview`.`tag` (
  `tagId` INT NOT NULL AUTO_INCREMENT,
  `threadId` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`tagId`),
  INDEX `fk_tag_thread1_idx` (`threadId` ASC) VISIBLE,
  CONSTRAINT `fk_tag_thread1`
    FOREIGN KEY (`threadId`)
    REFERENCES `myreview`.`thread` (`threadId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`thread` ;

CREATE TABLE IF NOT EXISTS `myreview`.`thread` (
  `threadId` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`threadId`),
  INDEX `fk_thread_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_thread_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`university`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`university` ;

CREATE TABLE IF NOT EXISTS `myreview`.`university` (
  `universityId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `acronym` VARCHAR(10) NULL,
  `province` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  PRIMARY KEY (`universityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`user` ;

CREATE TABLE IF NOT EXISTS `myreview`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `displayName` VARCHAR(45) NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `age` INT NULL,
  `universityId` INT NULL,
  `createdAt` DATETIME NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `verify` VARCHAR(5) NOT NULL,
  `kycVerify` VARCHAR(5) NOT NULL,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_user_university_idx` (`universityId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_role1_idx` (`roleName` ASC) VISIBLE,
  CONSTRAINT `fk_user_university`
    FOREIGN KEY (`universityId`)
    REFERENCES `myreview`.`university` (`universityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`roleName`)
    REFERENCES `myreview`.`role` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myreview`.`verification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myreview`.`verification` ;

CREATE TABLE IF NOT EXISTS `myreview`.`verification` (
  `verificationId` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`verificationId`),
  INDEX `fk_verification_user1_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fk_verification_user1`
    FOREIGN KEY (`userId`)
    REFERENCES `myreview`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
